module AsistenciaModule {
    interface AttendanceService {
        boolean markAttendance(in string userId, in string password);
        boolean isPresent(in string userId);
    };

    interface UserService {
        boolean registerUser(in string userId, in string password);
        boolean authenticateUser(in string userId, in string password);
    };
};
