module Asistencia {
    interface UsuarioService {
        boolean validarUsuario(in string idUsuario);
    };

    interface AsistenciaService {
        boolean registrarAsistencia(in string idUsuario);
        string generarReporte(in string idUsuario);
    };
};
